package com.tiernebre.tailgate.repository;

import java.util.Optional;

/**
 * Provides operations to perform on a set of data.
 *
 * @param <T> The entity to perform operations on.
 * @param <U> The primary identifier type of the entity.
 */
public interface Repository<T, U> {
    /**
     * Saves a given entity to a data store.
     *
     * @param entity The entity to save.
     * @return The entity that was saved, with values that could have been generated by the data store itself.
     */
    T saveOne(T entity);

    /**
     * Finds an entity by its given id.
     *
     * @param id The id of the entity to find.
     * @return An optional containing the found entity, OR if the entity was NOT found an empty optional.
     */
    Optional<T> findOneById(U id);

    /**
     * Updates a given entity using the identifier to determine an existing entity.
     *
     * @param entity The entity to update.
     * @return An optional containing the updated entity, OR if the entity was NOT found an empty optional.
     */
    Optional<T> updateOne(T entity);


    /**
     * Deletes an entity by its id.
     *
     * @param id The identifier of the entity to delete.
     * @return true if the entity was successfully deleted, false if not successful (for instance: the entity not existing).
     */
    Boolean deleteOneById(Long id);
}
