version: '3.9'

services:
    db:
        image: postgres:12.3
        ports:
            - "5454:5432"
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: zone-blitz
    smtp:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
