tailgate:
  jwt:
    secret: 'secretforjsonwebtokenswow'
    expiration-window-in-minutes: 15
  refresh-token:
    expiration-window-in-minutes: 30
  email:
    from: 'noreply@tailgate.io'
  user:
    confirmation:
      email:
        subject: 'Confirm your account with Tailgate'
        confirmationTokenTag: '{{ confirmationToken }}'
        message: 'Please go to https://tailgate.io/account/confirm/${tailgate.user.confirmation.email.confirmationTokenTag}'

spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5454/tailgate
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
