tailgate:
  jwt:
    secret: 'secretforjsonwebtokenswow'
    expiration-window-in-minutes: 15
  refresh-token:
    expiration-window-in-minutes: 30

spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5454/tailgate
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
