zone-blitz:
  jwt:
    secret: 'secretforjsonwebtokenswow'
    expiration-window-in-minutes: 15
  refresh-token:
    expiration-window-in-minutes: 30
  email:
    from: 'noreply@zoneblitz.app'
    host: 'localhost'
    port: 1025
  user:
    confirmation:
      email:
        subject: 'Confirm your account with Zone Blitz'
        confirmation-token-tag: '{{ confirmationToken }}'
        message: 'Please go to https://zoneblitz.app/account/confirm/{{ confirmationToken }}'
  password-reset:
    email:
      subject: 'Reset your password on Zone Blitz'
      password-reset-token-tag: '{{ passwordResetToken }}'
      message: 'Please go to https://zoneblitz.io/reset-password/{{ passwordResetToken }}'
    token:
      expiration-window-in-minutes: 20

spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5454/zone-blitz
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
